<div class="container mt-5">
<div class="alert alert-warning collapse" id="cannot">
 Attention Categorie associe à un produit !!
</div>
	<form method="post" id="form">
		<div class="form-group">
			<label for="nom">Nom</label>
			<input id="inputNom" value="<?=$this->produit ? $this->produit->nom : ''?>" name="nom" type="text" class="form-control" aria-describedby="nom" placeholder="Entrez nom">
			<div class="alert alert-danger collapse" id="nom">
			Remplir le nom
			</div>
		</div>
		<div class="form-group">
			<label for="description">Description</label>
			<input id="inputDesc" value="<?=$this->produit ? $this->produit->description : ''?>" name="description" type="text" class="form-control" id="description" placeholder="Description">
		<div class="alert alert-danger collapse" id="desc">
		Remplir la description
		</div>
		</div>
		<div class="form-group">
			<label for="prix">Prix</label>
			<input id="inputPrix" value="<?=$this->produit ? $this->produit->prix : ''?>" name="prix" type="text" class="form-control" placeholder="Prix">
			<div class="alert alert-danger collapse" id="prix">
			Remplir le prix
			</div>
			<div class="alert alert-danger collapse" id="prixNot">
			Prix  doit  etre un entier
			</div>
		</div>
		<div class="form-group">
			<label for="quantite">Quantité</label>
			<input id="inputQuantite" value="<?=$this->produit ? $this->produit->quantite : ''?>" name="quantite" type="text" class="form-control" placeholder="Quantité">
			<div class="alert alert-danger collapse" id="quantite">
			Remplir la quantite
			</div>
			<div class="alert alert-danger collapse" id="quantiteNot">
			Quantite  doit  etre un entier
			</div>
		</div>
		<div class="form-group">
			<select name="categorie" class="custom-select">
				<?php foreach ($this->categories as $c) {?>
				<option value="<?=$c->id?>" <?=$this->produit ? $this->produit->categorie->id == $c->id ? 'selected' : "" : ''?>><?=$c->nom?></option>
				<?php }?>
			</select>
		</div>
		<div class="form-group">
			<button name="<?=$this->action?>" class="btn btn-primary" type="submit" id="ajouter"><?=$this->action?></button>
			<a href="<?=$this->url(array('action' => 'get-produits'))?>" class="btn btn-outline-success">Retour à la liste</a>
		</div>
		
	</form>
</div>