<div class="container mt-5">
	<form method="post">
		<div class="form-group">
			<label for="nom">Nom</label>
			<input value="<?=$this->produit->nom?>" name="nom" type="text" class="form-control" id="nom" aria-describedby="nom" placeholder="Entrez nom">
		</div>
		<div class="form-group">
			<label for="description">Description</label>
			<input value="<?=$this->produit->description?>" name="description" type="text" class="form-control" id="description" placeholder="Description">
		</div>
		<div class="form-group">
			<label for="prix">Prix</label>
			<input value="<?=$this->produit->prix?>" name="prix" type="text" class="form-control" id="prix" placeholder="Prix">
		</div>
		<div class="form-group">
			<label for="quantite">Quantité</label>
			<input value="<?=$this->produit->quantite?>" name="quantite" type="text" class="form-control" id="quantite" placeholder="Quantité">
		</div>
		<div class="form-group">
			<select name="categorie" class="custom-select">
				<?php foreach($this->categories as $c) {?>
				<option value="<?=$c->id?>" <?=$this->produit->categorie->id == $c->id ? selected : ""?>><?=$c->nom?></option>
				<?php } ?>
			</select>
		</div>
		<div class="form-group">
			<button name="<?=$this->action?>" class="btn btn-primary" type="submit"><?=$this->action?></button>
			<a href="<?=$this->url(array('action'=>'get-produits'))?>" class="btn btn-outline-success">Retour à la liste</a>
		</div>
	</form>
</div>