<div class="container">
<h1>Categories</h1>
<br>
<div class="alert alert-danger collapse" id="supp">
  Categorie a été supprimé
</div>
<div class="alert alert-success collapse" id="aj">
  Categorie a été ajouté
</div>
<div class="alert alert-success collapse" id="mod">
  Categorie a été modifié
</div>
<div class="alert alert-warning collapse" id="cannot">
 Attention Categorie associe à un produit !!
</div>
<table class="table table-bordered">
  <thead>
    <tr>
	<th scope="col">Id</th>
	<th scope="col">Categorie</th>
	<th scope="col" colspan="2">Actions</th>
	<th scope="col" >Produits</th>
    </tr>
  </thead>
  <tbody style="background-color:#dadada;">
  <?php
  if(isset($this->info)) {
  foreach ($this->info as $cat) :
	echo "<tr>";
    echo "<tr>";
    echo  "<th scope='row'>$cat->id</th>";
    echo  "<td>$cat->nom</td>";
	echo  "<td><a href='modifier?idM=$cat->id' ><button type='button' class='btn btn-warning'>Modifier</button></a></td>";
	echo  "<td><a href='?idS=$cat->id' ><button type='button' class='btn btn-danger'>Supprimer</button></a></td>";
  echo "<td>";
  echo "<div style='vertical-align: top;text-align: center; display: inline;' >";
  if(isset($this->infoProd)) {
    foreach($this->infoProd as $prod) :
        if($prod->categorie->id == $cat->id) {
          echo "<img src='$prod->image'  style='width:65px ; height:85px;' />";
          echo "<div style='display:inline-block;' class='btn btn-link' data-toggle='modal' data-target='#exampleModal'>$prod->nom</div>";
        }
    endforeach;
  }
echo "<div>";
  echo "</td>";
  echo "</tr>";
 endforeach;
  }
  else {
	?>
    <tr>
      <td colspan="5">Aucun résultat</td>
    </tr>
  <?php }?>
  </tbody>
</table>
<center><a href="<?=$this->url(array('action'=>'modifier'))?>" ><button type='button' class='btn btn-primary'>Ajouter</button></a>
</div>