<div class="container-fluid mt-5">
<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
    <?php if ($flashMessenger->hasMessages('success')): ?>
    <div class="alert alert-success">
        <?php foreach ($flashMessenger->getMessages('success') as $msg): ?>
            <?php echo $msg ?>
        <?php endforeach; ?>
    </div>
    <?php endif; if ($flashMessenger->hasMessages('error')): ?>
        <div class="alert alert-danger">
            <?php foreach ($flashMessenger->getMessages('error') as $msg): ?>
                <?php echo $msg ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    
    <a href="<?=$this->url(array('action'=>'addproduit'))?>" class="btn btn-primary mb-3">Ajouter un produit</a>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Image</th>
                <th scope="col">Nom</th>
                <th scope="col">Description</th>
                <th scope="col">Prix</th>
                <th scope="col">Quantité</th>
                <th scope="col">Catégorie</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
        <?php
        if(isset($this->produits)) {
        foreach($this->produits as $p) { ?>
            <tr class="table-active">
                <th scope="row"><?=$p->id?></th>
                <th><img src="<?=$p->image?>" max-width="200px" height="100px"></img></th>
                <th><?=$p->nom?></th>
                <td><?=$p->description?></td>
                <td><?=$p->prix?> MAD</td>
                <td><?=$p->quantite?></td>
                <td><?=isset($p->categorie->nom) ? $p->categorie->nom : ''?></td>
                <td> 
                <a href="<?=$this->url(array('action'=>'addproduit'))?>?id=<?=$p->id?>" class="btn btn-warning">Modifier</a>
                <a class="btn btn-danger deleteProduct" value="<?=$p->id?>" data-toggle="modal" data-target="#deleteModal">Supprimer</a>
                </td>
            </tr>
        <?php }
        }
        else {
        ?>
        <tr>
            <td colspan="8">Aucun résultat</td>
        </tr>
        <?php } include("deleteproduit.phtml"); ?>
        </tbody>
    </table>    
</div>