<div class="container">

<br><br>

<div class="alert alert-danger collapse" id="inc">
  Categorie a été supprimé
</div>

<form method="post" action="categorie">
  <div class="form-group">
    <label for="exampleInputEmail1">Nom de la Categorie</label>
    <input type="text" class="form-control" name="nom"  value="<?php if(isset($this->catModif) && !empty($this->catModif)){ echo $this->catModif->nom;}?>">
	<input type="hidden" class="form-control" name="id"  value="<?php if(isset($this->catModif) && !empty($this->catModif)){ echo $this->catModif->id; }?>">
  </div>
  <br>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>