<div class="container">
	<form method="post">
		<div class="form-group">
			<label for="nom">Nom</label>
			<input name="nom" type="text" class="form-control" id="nom" aria-describedby="nom" placeholder="Entrez nom">
		</div>
		<div class="form-group">
			<label for="description">Description</label>
			<input name="description" type="text" class="form-control" id="description" placeholder="Description">
		</div>
		<div class="form-group">
			<label for="prix">Prix</label>
			<input name="prix" type="text" class="form-control" id="prix" placeholder="Prix">
		</div>
		<div class="form-group">
			<label for="quantite">Quantité</label>
			<input name="quantite" type="text" class="form-control" id="quantite" placeholder="Quantité">
		</div>
		<div class="form-group">
			<select name="categorie" class="custom-select">
				<option selected="">Catégorie</option>
				<?php foreach($this->categories as $c) {?>
				<option value="<?=$c->id?>"><?=$c->nom?></option>
				<?php } ?>
			</select>
		</div>
		<div class="form-group">
			<button name="Modifier" class="btn btn-info" type="submit">Modifier</button>
		</div>
	</form>
</div>