<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
  <head>
      <?php echo $this->HeadMeta(); ?>
      <?php echo $this->headTitle(); ?>
      <?php //echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
       </head>
  <body>
    <div class="container-fluid">
      <?=$this->layout()->content?>
    </div>
  </body>
</html>